### ISSUE TITLE
First time onConfigSet the oldValue is undefined

### ISSUE THREAD

**Issue by morko** [saviola777/haxball-headless-manager#14]
Expected the oldValue to contain the value set initially `room.pluginSpec.config` but instead it was `undefined`.

**Comment by saviola777** [comment]
Did your event conain a `paramName`? If there is a `paramName`, the `oldValue` should be correct. If it does not contain a `paramName`, then `oldValue` will always be `undefined` (can happen if the `pluginSpec` was set, for example, indicating that the whole config, or at least more than one parameter, was changed). How exactly does your `onConfigSet` handler look like? This problem can most likely be fixed by checking for the correct `paramName` first.

**Comment by morko** [comment]
Unfortunately I cannot seem to be able reproduce this.
