### ISSUE TITLE
HHM start workflow improvement for haxroomie

### ISSUE THREAD

**Issue by saviola777** [saviola777/haxball-headless-manager#31]
@morko I remember we talked about his a couple of months ago, there is currently some kind of workaround in place to prevent the HHM `start()` function from loading user plugins, but I couldn't find it anymore.

In the latest version of HHM it is possible to call `addPlugin()` before the `start()` function is called, these plugins are then loaded first when `start()` is called, before the user plugins. But I guess that would not be enough for your use case?

How should HHM handle startup to make things more convenient for you? Should I simply require calling `loadUserPlugins()` manually after `start()` has been called? Should I add a parameter in the `start()` function?

And remind me why you needed this again? :D I think it was something about injecting local plugins?

Related: #29

**Comment by morko** [comment]
Hey I don't remember exactly either, but there is a `plugins` property that you can pass to a `RoomController` in haxroomie that will eventually get handled in the `hhm-config.js`. The workaround I had to do to prevent the plugins to be loaded from the added repositories instead of the `plugins` property is here https://github.com/morko/haxroomie/blob/878778d2df2b300fec3ecf14f2598b9701c792c1/packages/haxroomie-core/src/browser/hhm-config.js#L41. 

The `plugins` property was pretty much undocumented in the first place and I think I am gonna deprecate it anyways in favour of actual repository. Therefore I don't think its neccessary to address this problem anymore and it was not a big deal anyways to handle it in the config. If you think this was not the thing we discussed about then please tell, because I am not sure.

**Comment by saviola777** [comment]
Sounds about right, thanks. I'll leave it as it is now, I'll add an issue about changing the way you load hr/core on your repo.
